### ISSUE TITLE
JisonLexerError: Lexical error on line 1: Unrecognized text

### ISSUE THREAD

**Issue by rahulvanmali21** [postcss/postcss-calc#101]
>   Erroneous area:
1: 1.6em + 0.75rem2px
^...........^
    at D:\css\app.css:31141:3
    at Object.parseError (D:\DigitalStationary\node_modules\postcss-calc\dist\parser.js:1164:15)
    at Object.lexer_parseError [as parseError] (D:\DigitalStationary\node_modules\postcss-calc\dist\parser.js:2297:44)
    at Object.lexer_next [as next] (D:\DigitalStationary\node_modules\postcss-calc\dist\parser.js:3292:22)
    at Object.lexer_fastLex [as fastLex] (D:\DigitalStationary\node_modules\postcss-calc\dist\parser.js:3367:18)
    at fastLex (D:\DigitalStationary\node_modules\postcss-calc\dist\parser.js:1567:27)
    at Parser.parse (D:\DigitalStationary\node_modules\postcss-calc\dist\parser.js:1641:30)
    at D:\DigitalStationary\node_modules\postcss-calc\dist\lib\transform.js:30:30
    at walk (D:\DigitalStationary\node_modules\postcss-value-parser\lib\walk.js:19:7)
    at ValueParser.walk (D:\DigitalStationary\node_modules\postcss-value-parser\lib\index.js:18:3)
    at transformValue (D:\DigitalStationary\node_modules\postcss-calc\dist\lib\transform.js:24:50)
    at _default (D:\DigitalStationary\node_modules\postcss-calc\dist\lib\transform.js:59:100)
    at D:\DigitalStationary\node_modules\postcss-calc\dist\index.js:25:51
    at D:\DigitalStationary\node_modules\postcss\lib\container.js:135:18
    at Rule.each (D:\DigitalStationary\node_modules\postcss\lib\container.js:101:16)
    at Rule.walk (D:\DigitalStationary\node_modules\postcss\lib\container.js:131:17)
    at D:\DigitalStationary\node_modules\postcss\lib\container.js:148:24
    at Root.each (D:\DigitalStationary\node_modules\postcss\lib\container.js:101:16)
    at Root.walk (D:\DigitalStationary\node_modules\postcss\lib\container.js:131:17)
    at D:\DigitalStationary\node_modules\postcss-calc\dist\index.js:23:9
    at initializePlugin (D:\DigitalStationary\node_modules\cssnano\dist\index.js:31:51)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ruibarbosareb** [comment]
same mistake.
Any solution?

**Comment by iamnimnul** [comment]
Same here ;)

```
🚨  /app/frontend/src/assets/css/main.scss:undefined:undefined: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 1.5em + 0.75rem2px
^...........^

  Erroneous area:
1: 1.5em + 0.75rem2px
^...........^
    at /app/frontend/src/assets/css/main.scss:1988:3
    at Object.parseError (/app/frontend/node_modules/postcss-calc/dist/parser.js:1164:15)
    at Object.lexer_parseError [as parseError] (/app/frontend/node_modules/postcss-calc/dist/parser.js:2297:44)
    at Object.lexer_next [as next] (/app/frontend/node_modules/postcss-calc/dist/parser.js:3292:22)
    at Object.lexer_fastLex [as fastLex] (/app/frontend/node_modules/postcss-calc/dist/parser.js:3367:18)
    at fastLex (/app/frontend/node_modules/postcss-calc/dist/parser.js:1567:27)
    at Parser.parse (/app/frontend/node_modules/postcss-calc/dist/parser.js:1641:30)
    at /app/frontend/node_modules/postcss-calc/dist/lib/transform.js:30:30
    at walk (/app/frontend/node_modules/postcss-value-parser/lib/walk.js:19:7)
    at ValueParser.walk (/app/frontend/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/app/frontend/node_modules/postcss-calc/dist/lib/transform.js:24:50)
npm ERR! code ELIFECYCLE
```

I'm using parceljs 1.12.4, node v10.16.0, npm 6.9.0 on docker node:10-alpine image. It's bootstrap code causing a problem:
https://github.com/twbs/bootstrap/blob/v4.3.1/dist/css/bootstrap.css#L1860
or
https://github.com/twbs/bootstrap/blob/v4.3.1/scss/_variables.scss#L495

**Comment by iamnimnul** [comment]
Solution is on parceljs website:
https://parceljs.org/css.html#set-cssnano-minify-config

create a file `cssnano.config.js` next to package.json with a content:

```
module.exports = {
  preset: [
    'default',
    {
      calc: false,
      discardComments: {
        removeAll: true
      }
    }
  ]
};
```

**Comment by jasminexie** [comment]
The current master branch of postcss calc has fixed these errors. I believe there are difficulties that prevent the maintainer from publishing; you can either specify postcss calc to point to this github repo, or you can disable it.

**Comment by evilebottnawi** [comment]
https://github.com/cssnano/cssnano/issues/833

**Comment by ludofischer** [comment]
Not enough info to reproduce, the bootstrap code pointed at in one comment compiles as of postcss-calc 8.2.0 Since https://github.com/postcss/postcss-calc/pull/137 postcss-calc should not throw when encountering invalid CSS.
