### ISSUE TITLE
 FATAL  Nuxt build error

### ISSUE THREAD

**Issue by thisVioletHydra** [postcss/postcss-calc#131]
### package.json 
```json
  "postcss-at-rules-variables": "^0.2.1",
    "postcss-combine-duplicated-selectors": "^10.0.2",
    "postcss-css-variables": "^0.17.0",
    "postcss-custom-properties": "^11.0.0",
    "postcss-each": "^1.0.0",
    "postcss-for": "^2.1.1",
    "postcss-gap-properties": "^2.0.0",
    "postcss-hexrgba": "^2.0.1",
    "postcss-import": "14.0.0",
    "postcss-loader": "4.1.0",
    "postcss-mixins": "^7.0.3",
    "postcss-nested": "^5.0.5",
    "postcss-preset-env": "^6.7.0",
    "postcss-pxtorem": "^5.1.1",
    "postcss-responsive-type": "^1.0.0",
    "postcss-safe-parser": "^5.0.2",
    "postcss-sorting": "^6.0.0",
    "postcss-url": "10.1.1",
```

### build: 
```js
{
  'postcss-at-rules-variables': {},
  'postcss-css-variables': {},
  

  'postcss-url': {},
  'postcss-import': {},
  'postcss-nested': {},

  'postcss-mixins': {
    mixinsDir: rootNoExt({ name: 'mixins', type: 'pcss' }),
  },

  'postcss-responsive-type': {},
  'postcss-hexrgba': {},

  'postcss-sorting': {
    'properties-order': [
      'display',
      'margin',
      'padding',
      'border',
      'background',
      // nuxt
    ],
  },
  'postcss-pxtorem': {
    rootValue: 16,
    propList: ['font', 'font-size', 'line-height', 'letter-spacing', 'margin', 'padding'],
  },
  'postcss-gap-properties': {},
  'postcss-calc': {},
  'postcss-for': {},
  'postcss-each': {},
  'postcss-combine-duplicated-selectors': {},
};
```

### postcss
```postcss
:root {
  --main-font-size: 1rem;
}


@each $el, $dex in '', 2.5, 2.05, 1.6, 1.23, 0.95, 0.7 {
  h$(dex) {
    --tmp-elem: $el;

    font-size: calc(var(--main-font-size) * var(--tmp-elem));
  }
}
```

### terminal

```node
ERROR in ./assets/pcss/index.pcss (./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/postcss-loader/dist/cjs.js??ref--4-oneOf-1-2!./assets/pcss/index.pcss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 1rem * $el
^.........^
    at C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\assets\pcss\index.pcss:32:5
    at Object.parseError (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\dist\parser.js:1200:15)
    at Object.lexer_parseError [as parseError] (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\dist\parser.js:2333:44)
    at Object.lexer_next [as next] (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\dist\parser.js:3328:22)
    at Object.lexer_fastLex [as fastLex] (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\dist\parser.js:3403:18)
    at fastLex (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\dist\parser.js:1603:27)
    at Parser.parse (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\dist\parser.js:1677:30)
    at C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\dist\lib\transform.js:33:30
    at walk (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\node_modules\postcss-value-parser\lib\walk.js:7:16)
    at ValueParser.walk (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\node_modules\postcss-value-parser\lib\index.js:18:3)
    at transformValue (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\dist\lib\transform.js:24:50)
    at _default (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\dist\lib\transform.js:66:100)
    at C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss-calc\dist\index.js:27:32
    at C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss\lib\container.js:74:18
    at Rule.each (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss\lib\container.js:60:16)
    at Rule.walk (C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss\lib\container.js:71:17)
    at C:\FRONTEND\www\group-dashboard\group-dashboard-siteanalyzer\node_modules\postcss\lib\container.js:79:24
 @ ./assets/pcss/index.pcss 4:14-163
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

 FATAL  Nuxt build error                                                                                      11:32:24

  at WebpackBundler.webpackCompile (node_modules\@nuxt\webpack\dist\webpack.js:2125:21)
  at processTicksAndRejections (node:internal/process/task_queues:94:5)
  at async WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:2074:5)
  at async Builder.build (node_modules\@nuxt\builder\dist\builder.js:327:5)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-build.js:110:7)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

error Command failed with exit code 1.
```

**Comment by thisVioletHydra** [comment]
rip ☠
