### ISSUE TITLE
Parse error with nested calc and CSS custom properties

### ISSUE THREAD

**Issue by wessberg** [postcss/postcss-calc#77]
The following CSS:

```css
div {
  margin-right: calc(var(--a) - var(--b, calc(var(--c) * 20)));
}
```

Leads to the following parser error:

```
JisonParserError: Parse error on line 1: 
var(--a) - var(--b, calc(var(--c)*20))
-------------------------------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN"
```

Looking at the Stack trace, here's the chain of the last few operations leading to the issue:

```
at Parser.parseError (/node_modules/postcss-calc/dist/parser.js:1164:15)
at Parser.parse (/node_modules/postcss-calc/dist/parser.js:1680:30)
at /node_modules/postcss-calc/dist/lib/transform.js:30:30
```

Removing the last `*20` part removes the parser error.

**Comment by evilebottnawi** [comment]
Thanks for issue, it is bug

**Comment by eric1iu** [comment]
Looks like the same error for this:
```
JisonParserError: Parse error on line 1: 
  max(5px, calc(env(safe-area-inset-right) - 4px))
  -----------------------------------------------^
  Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN"
```

**Comment by evilebottnawi** [comment]
Yes, right now i rewrite plugin and parser, i think release will be on end of week or next week

**Comment by eric1iu** [comment]
As a workaround, disable `postcss-calc` in `package.json` to pass `gatsby build` in my case.
```json
  "cssnano": {
    "preset": [
      "default",
      {
        "calc": false
      }
    ]
  }
```

Will enable again once this bug fixed. Thanks!

**Comment by drinchev** [comment]
Btw I have the very same problem without having nested variables : 

```
const postcssCalc = require('postcss-calc');

const css = `
.baz{
  height:calc( calc(16px + 0.8)+calc(1.5 + 0.9));
}
`

postcssCalc.process( css ).catch( error => console.error(error.toString()) );
```

This breaks with error : 

```
JisonParserError: Parse error on line 1:
calc(16px + 0.8)2.4
----------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "NUMBER"
```

I assume having nested calc with no space between breaks it, since

```
height:calc( calc(16px + 0.8)+ calc(1.5 + 0.9));
//                            ^ note space
```

works normally.

**Comment by evilebottnawi** [comment]
@drinchev feel free to send a PR

**Comment by drinchev** [comment]
@evilebottnawi Actually my bug is unrelated to this one. 

Just checked and it seems to work with the latest master branch. 

```

test(
  'should handle nested calc statements with 2 calc parameters',
  testValue,
  'calc(calc(16px + 0.8)+ calc(1.5 + 0.9))',
  'calc(16px + 3.2)'
);

test(
  'should handle nested calc statements with 2 calc parameters with no spaces',
  testValue,
  'calc( calc(16px + 0.8)+calc(1.5 + 0.9))',
  'calc(16px + 3.2)'
);
```

Both tests work on current `master`, but don't pass in `7.0.1` tag.

Any plans to release soon? 

*7.0.1* is dependency of the current `cssnano`, which is dependency of the current `create-react-app`.

**Comment by evilebottnawi** [comment]
@drinchev thanks for investigate looks on this in near future

**Comment by rrhythmsharma** [comment]
@wessberg, Thanks for opening this issue. I was also struggling with same calc() issue inside CSS file

**Comment by GreenGremlin** [comment]
I get a similar error when using css-loader's @value properties in calc functions.

```css
@value avatar-size: 36px;

.avatar {
  width: avatar-size;
  height: avatar-size;
  margin-top: calc((avatar-size) / 2);
}
```

Results in this error

```
  Erroneous area:
1: (avatar-size) / 2
^...^
    at Object.parseError (/Users/jonathan/app/node_modules/postcss-calc/dist/parser.js:1164:15)
    at Object.lexer_parseError [as parseError] (/Users/jonathan/app/node_modules/postcss-calc/dist/parser.js:2297:44)
    at Object.lexer_next [as next] (/Users/jonathan/app/node_modules/postcss-calc/dist/parser.js:3292:22)
    at Object.lexer_fastLex [as fastLex] (/Users/jonathan/app/node_modules/postcss-calc/dist/parser.js:3367:18)
    at fastLex (/Users/jonathan/app/node_modules/postcss-calc/dist/parser.js:1567:27)
    at Parser.parse (/Users/jonathan/app/node_modules/postcss-calc/dist/parser.js:1641:30)
    at /Users/jonathan/app/node_modules/postcss-calc/dist/lib/transform.js:33:28
    at walk (/Users/jonathan/app/node_modules/postcss-value-parser/lib/walk.js:19:7)
    at ValueParser.walk (/Users/jonathan/app/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/Users/jonathan/app/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/Users/jonathan/app/node_modules/postcss-calc/dist/lib/transform.js:66:100)
    at /Users/jonathan/app/node_modules/postcss-calc/dist/index.js:25:51
    at /Users/jonathan/app/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/jonathan/app/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/Users/jonathan/app/node_modules/postcss/lib/container.js:131:17)
    at /Users/jonathan/app/node_modules/postcss/lib/container.js:148:24
    at Root.each (/Users/jonathan/app/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/jonathan/app/node_modules/postcss/lib/container.js:131:17)
    at /Users/jonathan/app/node_modules/postcss-calc/dist/index.js:23:9
    at initializePlugin (/Users/jonathan/app/node_modules/cssnano/dist/index.js:31:51)
```

The @value properties are processed by css-loader, which runs after postcss-loader. If nothing else, it seems appropriate for postcss-calc to just ignore calc values that fail to parse.

**Comment by GreenGremlin** [comment]
I was able to work around my issue by including the postcss-modules-values plugin before postcss-calc.

**Comment by HZooly** [comment]
Any example of this for removing postcss-calc from Gatsby build please? I can't achieve this...

**Comment by Semigradsky** [comment]
This bug happens because 'function' regexp not matching function which has many brackets inside: https://github.com/postcss/postcss-calc/blob/6260789750bbf73006190ef00ab43abfb278b4dc/src/parser.jison#L13

As I understand it is not possible to match nested brackets by regex so it should be rewritten from regex.

**Comment by while0pass** [comment]
I get the following error:
```css
:root {
  /* ... */
  --main-gap-mobile: calc((100vw - var(--main-width-mobile)) / 2);
}
```

```
JisonParserError in plugin "gulp-postcss"
Message:
    Parse error on line 1:
- calc((100v...
--^
Expecting "ADD", "SUB", "LENGTH", "ANGLE", "TIME", "FREQ", "RES", "UNKNOWN_DIMENSION", "EMS", "EXS", "CHS", "REMS", "VHS", "VWS", "VMINS", "VMAXS", "PERCENTAGE", "NUMBER", "dimension", got unexpected "CALC"
Details:
    hash: [object Object]
    fileName: ./src/styles/main.css
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

Stack:
JisonParserError: Parse error on line 1:
- calc((100v...
--^
Expecting "ADD", "SUB", "LENGTH", "ANGLE", "TIME", "FREQ", "RES", "UNKNOWN_DIMENSION", "EMS", "EXS", "CHS", "REMS", "VHS", "VWS", "VMINS", "VMAXS", "PERCENTAGE", "NUMBER", "dimension", got unexpected "CALC"
    at Parser.parseError (./node_modules/postcss-calc/dist/parser.js:1200:15)
    at Parser.parse (./node_modules/postcss-calc/dist/parser.js:1716:30)
    at ./node_modules/postcss-calc/dist/lib/transform.js:33:30
    at walk (./node_modules/postcss-calc/node_modules/postcss-value-parser/lib/walk.js:7:16)
    at ValueParser.walk (./node_modules/postcss-calc/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (./node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (./node_modules/postcss-calc/dist/lib/transform.js:66:100)
    at ./node_modules/postcss-calc/dist/index.js:27:32
    at ./node_modules/postcss-import/node_modules/postcss/lib/container.js:144:26
    at Rule.each (./node_modules/postcss-import/node_modules/postcss/lib/container.js:110:22)```

**Comment by julmot** [comment]
In my case it was caused by a third party library: https://github.com/sampotts/plyr/issues/1816

**Comment by treyg** [comment]
I'm running into this error using gridsome with a bootstrap theme and can't seem to find the solution. 

Getting ``` Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "REMS"```

**Comment by jpabeem** [comment]
It seems wrapping a variable inside `#{}` (fix: https://github.com/creativetimofficial/ct-light-bootstrap-dashboard-pro-react/issues/37#issuecomment-478605836 ) was able to solve my issue.

**Comment by wongjn** [comment]
As per [Semigradsky's comment](#issuecomment-587312626), I think it is something to do with when there are too many parenthesis levels in the formula:

```
var(--a) + max(1px, min((1vw - 5.9px), 10px))
--------------------------------------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN"
```

**Comment by Pomax** [comment]
Hm, looking at this issue, all these `calc()` instructions aren't valid as per the CSS spec, which SCSS still has to obey, so this doesn't look like a bug in flagging errors, but a bug in how it's reporting _what_ is wrong?

- `margin-right: calc(var(--b, calc(var(--c) * 1)));` is missing "stuff" `var(--b`, as stated, it isn't a valid calc statement.
- `height: calc( calc(16px + 0.8)+calc(1.5 + 0.9));` does not have spaces around the `+`, which is required by the CSS spec
- parentheses are active syntax for calc, so `margin-top: calc((avatar-size) / 2);` isn't valid syntax.
- which you also see for `--main-gap-mobile: calc((100vw - var(--main-width-mobile)) / 2);`, where `(100vw - var(--main-width-mobile))` should be `calc(100vw - var(--main-width-mobile))`.

**Comment by Semigradsky** [comment]
`margin-right: calc(var(--b, calc(var(--c) * 1)))` and `--main-gap-mobile: calc((100vw - var(--main-width-mobile)) / 2)` are valid. You can check it just by add them via chrome devtools.

**Comment by Pomax** [comment]
You're right - although that first one still makes no sense: those `calc()` wrappers do nothing, and a decent tool would remove them since `calc(var(--b, calc(var(--c) * 1)))` is identical to `var(--b, var(--c))`.

**Comment by jojoghaida** [comment]
Is this issue fixed? I resolve this issue for my app a year ago by adding:

> As a workaround, disable `postcss-calc` in `package.json` to pass `gatsby build` in my case.
> 
> ```json
>   "cssnano": {
>     "preset": [
>       "default",
>       {
>         "calc": false
>       }
>     ]
>   }
> ```
> 
> Will enable again once this bug fixed. Thanks!

but I've update some packages and now this issue is back. I still have the above in my package.json. My issue is only happening in react-scripts-build. I'm running postcss v8.1.14 and postcss-calc v7.0.5... 

This is really causing me a lot of problems if someone can point me to a new way of disabling the parser on react-script-build that will be greatly appreciated.

**Comment by bwstoppel** [comment]
In case this helps anyone, `calc(var(--base-padding) * -1)` throws an error whereas `calc(-1 * var(--base-padding))` does not.

**Comment by ludofischer** [comment]
> In case this helps anyone, calc(var(--base-padding) * -1) throws an error whereas calc(-1 * var(--base-padding)) does not.

But does it just print an error message or does it crash?

**Comment by bwstoppel** [comment]
> 

It fails and prints a generic error. Something like "failed at line 1 column 26." I don't have the error in front of me anymore. The error message was not accurate. I found the issue by removing and adding back styles until I narrowed it down to the culprit.

**Comment by marcelomatheus** [comment]
> As a workaround, disable `postcss-calc` in `package.json` to pass `gatsby build` in my case.
> 
>   "cssnano": {
>     "preset": [
>       "default",
>       {
>         "calc": false
>       }
>     ]
>   }
> Will enable again once this bug fixed. Thanks!

Thanks, it worked for me

**Comment by FeBe95** [comment]
Another example that causes a warning to be reported:
```scss
.serp-product-rank {
  --best-rank: 1;
  --worst-rank: 40;
  --rank-to-hsl: calc(max(0, 100 * (var(--worst-rank) - var(--serp-product-rank, 0)) / (var(--worst-rank) - var(--best-rank))));
  
  background-color: hsl(var(--rank-to-hsl) 100% 40%);
```

I didn't want to completely disable `postcss-calc`. My solution: break down the calculation into individual parts like this:
```scss
.serp-product-rank {
  --best-rank: 1;
  --worst-rank: 40;

  // Break down the HSL calculation into individual parts, so that "postcss-calc" doesn't fail
  --rank-range: calc(var(--worst-rank) - var(--best-rank));
  --rank-difference: calc(var(--worst-rank) - var(--serp-product-rank, 0));
  --rank-ratio: calc(var(--rank-difference) / var(--rank-range));
  --rank-percentage: calc(100 * var(--rank-ratio));
  --rank-to-hsl: calc(max(0, var(--rank-percentage)));

  background-color: hsl(var(--rank-to-hsl) 100% 40%);
}
````

**Comment by ludofischer** [comment]
> I didn't want to completely disable postcss-calc. My solution: break down the calculation into individual parts like this:

As far as I know, postcss-calc leaves the CSS it does not understand untouched, the warning is just a warning, it does not mean the output is invalid. Looks like your solution might increase the CSS output size.

**Comment by ludofischer** [comment]
Fixed in new parser
