### ISSUE TITLE
JisonLexerError: Lexical error on line 1: Unrecognized text

### ISSUE THREAD

**Issue by qlerebours** [postcss/postcss-calc#89]
I've got a NextJS project where I'm using `withCss` and `withSass` that seems to use `postcss-calc` to during the project's build.

When building I've got the following error as soon as I use `calc` functions:

```
> Failed to build
{ JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 100VH - 30px
^..^
    at /home/qlerebours/Projects/TraveledMap/traveledmap/src/app/static/chunks/styles.2606b0eb.chunk.css:8106:7
    at Object.parseError (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-calc/dist/parser.js:1164:15)
    at Object.lexer_parseError [as parseError] (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-calc/dist/parser.js:2297:44)
    at Object.lexer_next [as next] (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-calc/dist/parser.js:3292:22)
    at Object.lexer_fastLex [as fastLex] (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-calc/dist/parser.js:3367:18)
    at fastLex (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-calc/dist/parser.js:1567:27)
    at Parser.parse (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-calc/dist/parser.js:1641:30)
    at /home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-calc/dist/lib/transform.js:30:30
    at walk (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-value-parser/lib/walk.js:19:7)
    at ValueParser.walk (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-calc/dist/lib/transform.js:59:100)
    at /home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss-calc/dist/index.js:25:51
    at /home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss/lib/container.js:131:17)
    at /home/qlerebours/Projects/TraveledMap/traveledmap/src/app/node_modules/postcss/lib/container.js:148:24
  hash: 
   { errStr: 'Lexical error on line 1: Unrecognized text.\n\n  Erroneous area:\n1: 100VH - 30px\n^..^',
     recoverable: false,
     text: '',
     token: null,
     line: 0,
     loc: 
      { first_line: 1,
        first_column: 0,
        last_line: 1,
        last_column: 0,
        range: [Array] },
     yy: 
      { parseError: undefined,
        quoteName: undefined,
        lexer: undefined,
        parser: undefined,
        pre_parse: undefined,
        post_parse: undefined,
        pre_lex: undefined,
        post_lex: undefined },
     lexer: 
      { yy: {},
        __decompressed: true,
        _input: '',
        yytext: '',
        yyleng: 0,
        match: '',
        matches: false,
        _more: false,
        _backtrack: false,
        yylloc: [Object],
        _signaled_error_token: false,
        done: false,
        yylineno: 0,
        matched: '',
        conditionStack: [Array],
        __currentRuleSet__: null,
        offset: 0 },
     destroy: [Function: destructLexErrorInfo] },
  postcssNode: 
   Declaration {
     raws: { before: '\n      ', between: ':' },
     type: 'decl',
     parent: 
      Rule {
        raws: [Object],
        type: 'rule',
        nodes: [Array],
        parent: [Object],
        source: [Object],
        selector: '.bottom-content-wrapper .slider-wrapper.visible',
        lastEach: 9,
        indexes: [Object] },
     source: { start: [Object], input: [Object], end: [Object] },
     prop: 'max-height',
     value: 'calc(100VH - 30px)' } }
error Command failed with exit code 1.
```

The source code:
```
&.visible {
      height: 165px;
      max-height: calc(100VH - 30px);
}
```

The `chunk.css` file:
```
.bottom-content-wrapper .slider-wrapper.visible {
      height: 165px;
      max-height: calc(100VH - 30px); }
```

This is not the first time that I have this error, as I said as soon as I want to use calc, my build fails because of this error

**Comment by evilebottnawi** [comment]
bug, feel free to send a PR

**Comment by qlerebours** [comment]
I'd like to, but I really don't know how to fix it

**Comment by ILokalin** [comment]
I have a similar error in mixins. For solve this problem I use standard math operators for scss/sass (without "calc"):
```
.class-scss {
  width: 100% - 30px;
}

.class-sass
  width: 100% - 30px
```

**Comment by binaykmr06** [comment]
all the **VH** should replace to vh.

It'll work.

**Comment by wufeng87** [comment]
same problem here. I use `vh`.
```
JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 100vh - 9@size-8
^...........^
    at /Users/hjm/Documents/code/yuannian/fssc-web/high/css/78_68a44f35d842fd820357.css:1103:3
    at Object.parseError (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:1164:15)
    at Object.lexer_parseError [as parseError] (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:2297:44)
    at Object.lexer_next [as next] (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:3292:22)
    at Object.lexer_fastLex [as fastLex] (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:3367:18)
    at fastLex (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:1567:27)
    at Parser.parse (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:1641:30)
    at /Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/lib/transform.js:30:30
    at walk (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-value-parser@3.3.1@postcss-value-parser/lib/walk.js:19:7)
    at ValueParser.walk (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-value-parser@3.3.1@postcss-value-parser/lib/index.js:18:3)
    at transformValue (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/lib/transform.js:24:50)
    at _default (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/lib/transform.js:59:100)
    at /Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/index.js:25:51
    at /Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:135:18
    at Rule.each (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:101:16)
    at Rule.walk (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:131:17)
    at /Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:148:24
    at Root.each (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:101:16)
    at Root.walk (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:131:17)
    at /Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/index.js:23:9
    at initializePlugin (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_cssnano@4.1.10@cssnano/dist/index.js:31:51)
```

**Comment by Semigradsky** [comment]
@wufeng87 could you provide part of css code where you get this error?

**Comment by nachogarcia** [comment]
Same here, using Nuxt. `min-height: calc(100vh - $footer-height - $header-height - $header-margin);`

**Comment by binaykmr06** [comment]
> same problem here. I use `vh`.
> 
> ```
> JisonLexerError: Lexical error on line 1: Unrecognized text.
> 
>   Erroneous area:
> 1: 100vh - 9@size-8
> ^...........^
>     at /Users/hjm/Documents/code/yuannian/fssc-web/high/css/78_68a44f35d842fd820357.css:1103:3
>     at Object.parseError (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:1164:15)
>     at Object.lexer_parseError [as parseError] (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:2297:44)
>     at Object.lexer_next [as next] (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:3292:22)
>     at Object.lexer_fastLex [as fastLex] (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:3367:18)
>     at fastLex (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:1567:27)
>     at Parser.parse (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/parser.js:1641:30)
>     at /Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/lib/transform.js:30:30
>     at walk (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-value-parser@3.3.1@postcss-value-parser/lib/walk.js:19:7)
>     at ValueParser.walk (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-value-parser@3.3.1@postcss-value-parser/lib/index.js:18:3)
>     at transformValue (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/lib/transform.js:24:50)
>     at _default (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/lib/transform.js:59:100)
>     at /Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/index.js:25:51
>     at /Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:135:18
>     at Rule.each (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:101:16)
>     at Rule.walk (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:131:17)
>     at /Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:148:24
>     at Root.each (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:101:16)
>     at Root.walk (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss@7.0.23@postcss/lib/container.js:131:17)
>     at /Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_postcss-calc@7.0.1@postcss-calc/dist/index.js:23:9
>     at initializePlugin (/Users/hjm/Documents/code/yuannian/fssc-web/high/node_modules/_cssnano@4.1.10@cssnano/dist/index.js:31:51)
> ```

What is 9 in 9@size-8

**Comment by binaykmr06** [comment]
> Same here, using Nuxt. `min-height: calc(100vh - $footer-height - $header-height - $header-margin);`

use variables in _ not in -

**Comment by kevinisaac** [comment]
Any update here? Using `calc(100vh - $headerheight)` but getting the same error.

**Comment by h-sada** [comment]
@kevinisaac 
https://github.com/creativetimofficial/ct-light-bootstrap-dashboard-pro-react/issues/37

use `#{}` in calc like this
`calc(100vh - #{$}headerheight)`

I've also tried this and done successfully.

**Comment by chetanku** [comment]
I get this error on line "calc(100% - $icon-size-lg - 1)" , I made it calc(100% - #{$icon-size-lg} - 1) but i still get the same issue, Can someone help ? @h-sada

**Comment by janlent1** [comment]
@alexander-akait 

Still having this error when using  CssMinimizerPlugin and having calc(100% - 10px)
Do you might have an idea why this is the case?
Thanks and Best,
Jan

**Comment by ludofischer** [comment]
Can't get any error with `calc(100% -10px)` on postcss-calc 8.2. Other issues seem related to passing Sass to postcss-calc without replacing the Sass variables first. Crash should be fixed in https://github.com/postcss/postcss-calc/pull/137
